/* ──────────────────────────────────────────────────────────────────────────
   Insights — the long-form articles behind the cards on the landing page.

   Every figure quoted here is produced by AlphaForge's own engine, not
   invented for copy. The charts in public/insights/ are generated by
   `scripts/make_insight_charts.py`, which imports core.honesty and
   core.backtest_engine directly — so the article, the picture and the product
   can't drift apart.
   ────────────────────────────────────────────────────────────────────────── */

export type Block =
  | { kind: "p"; text: string }
  | { kind: "h"; text: string }
  | { kind: "list"; items: string[] }
  | { kind: "quote"; text: string }
  | { kind: "callout"; title: string; text: string }
  | { kind: "table"; head: string[]; rows: string[][]; caption?: string };

export type Article = {
  slug: string;
  tag: string;
  accent: string;
  readMinutes: number;
  title: string;
  dek: string;
  /** Short version used on the landing-page card. */
  excerpt: string;
  image: string;
  imageAlt: string;
  imageCaption: string;
  body: Block[];
  references: { text: string }[];
  /** Which module in the product does this? */
  tryIt: { label: string; href: string };
};

export const ARTICLES: Article[] = [
  {
    slug: "why-your-best-backtest-is-your-worst-strategy",
    tag: "Overfitting",
    accent: "#00f5a0",
    readMinutes: 6,
    title: "Why your best backtest is probably your worst strategy",
    dek: "Search hard enough and something will look brilliant by pure chance. Here is how much Sharpe you get for free, and what the Deflated Sharpe Ratio does about it.",
    excerpt:
      "Try enough parameter combinations and one will look brilliant by pure chance. Here's how the Deflated Sharpe Ratio prices that illusion in.",
    image: "/insights/overfitting.png",
    imageAlt:
      "Chart: the best Sharpe ratio expected from luck alone rises from 0 at one trial to 0.79 at ten trials, 1.26 at a hundred and 1.63 at a thousand.",
    imageCaption:
      "Computed with core.honesty._expected_max_sharpe — the same function the Deflated Sharpe Ratio uses to discount a result for multiple testing.",
    body: [
      {
        kind: "p",
        text: "Here is an uncomfortable experiment. Generate a thousand strategies that have no edge whatsoever — pure noise, expected return exactly zero. Backtest all of them. Then keep the best one and put its equity curve on a slide.",
      },
      {
        kind: "p",
        text: "That curve will look good. Not marginally good — investable good. The chart above is that experiment run through AlphaForge's own maths. With ten variations tried, the luckiest one is expected to post a Sharpe of about 0.79. At a hundred, 1.26. At a thousand, 1.63. None of them can predict anything. The number is manufactured entirely by the search.",
      },
      {
        kind: "callout",
        title: "The thing worth internalising",
        text: "A Sharpe of 1.6 sounds like skill. After a thousand attempts it is the median outcome of having no skill at all. The Sharpe ratio alone cannot tell those two situations apart, because it does not know how many times you looked.",
      },
      { kind: "h", text: "Why the usual defences don't work" },
      {
        kind: "p",
        text: "The instinctive answers are to hold out a test set, or to demand a longer history. Both help, and neither is sufficient, because the searching does not stop. You look at the held-out result, adjust something, and look again. After the fifth adjustment the hold-out has quietly become part of the training set. The statistical term is multiple testing; the practical term is that you have been fitting the answer.",
      },
      {
        kind: "p",
        text: "This is not a retail-trader failing. It is the central finding of a body of work by Bailey and López de Prado, who argue that most published backtests in quantitative finance are unreliable for exactly this reason, and that a backtest without a trial count attached is not interpretable.",
      },
      { kind: "h", text: "What AlphaForge does instead" },
      {
        kind: "p",
        text: "Three measurements, all of which live in core/honesty.py and run on every backtest:",
      },
      {
        kind: "list",
        items: [
          "Probabilistic Sharpe Ratio — the probability the true Sharpe is above zero, given the length of the sample and the skew and fat tails in the returns. A short, lumpy track record is penalised.",
          "Deflated Sharpe Ratio — the PSR with the benchmark raised to the Sharpe you would expect from luck after N trials. This is the chart above turned into a hurdle. The more you searched, the higher the bar.",
          "Probability of Backtest Overfitting — via combinatorially symmetric cross-validation: split the history many ways, and ask how often the configuration that ranked best in-sample lands in the bottom half out-of-sample. If that happens most of the time, the selection process itself is broken.",
        ],
      },
      {
        kind: "p",
        text: "The engine then adds two blunt questions that have nothing to do with statistics: would the drawdown have ended your account, and does the thing actually beat buy-and-hold after real costs. A strategy has to pass all of it before the verdict reads PROBABLY REAL.",
      },
      { kind: "h", text: "How to read your own verdict" },
      {
        kind: "table",
        head: ["What you see", "What it means"],
        rows: [
          ["DSR near 0%", "After accounting for the search, the edge is indistinguishable from luck. This is the common case."],
          ["PBO above ~50%", "The winner in-sample tends to be a loser out-of-sample. The ranking is noise."],
          ["High Sharpe, low DSR", "The classic overfit signature: an impressive number that does not survive the trial-count correction."],
          ["Blew up = YES", "A drawdown past 50%. Statistical significance is irrelevant if you would have stopped trading."],
        ],
      },
      {
        kind: "quote",
        text: "The honest response to a low Deflated Sharpe is not to search harder for a configuration that scores well. It is to accept that this family of rules, on this instrument, does not have the edge you were hoping for.",
      },
      {
        kind: "p",
        text: "That is a genuinely useful outcome. Knowing an idea is empty costs you an afternoon. Discovering it live costs considerably more.",
      },
    ],
    references: [
      { text: "Bailey, D. & López de Prado, M. (2012). The Sharpe Ratio Efficient Frontier — the Probabilistic Sharpe Ratio." },
      { text: "Bailey, D. & López de Prado, M. (2014). The Deflated Sharpe Ratio: Correcting for Selection Bias, Backtest Overfitting and Non-Normality." },
      { text: "Bailey, D., Borwein, J., López de Prado, M. & Zhu, Q. The Probability of Backtest Overfitting (combinatorially symmetric cross-validation)." },
    ],
    tryIt: { label: "Run the Honesty Engine", href: "/features/honesty-engine" },
  },

  {
    slug: "what-a-trade-really-costs-in-india",
    tag: "Costs",
    accent: "#0be0ff",
    readMinutes: 5,
    title: "The 0.21% lie: what a trade really costs in India",
    dek: "Brokerage is the small part. Once STT, stamp duty, exchange and SEBI fees, GST and slippage are counted, a delivery round trip costs 0.394% — and that gap decides which strategies survive.",
    excerpt:
      "Brokerage is the small part. STT, stamp duty, SEBI charges, GST and slippage push a real delivery round trip to 0.394% — and that gap kills most high-turnover edges.",
    image: "/insights/costs.png",
    imageAlt:
      "Stacked bar of a round-trip trade cost in India: slippage 0.200%, STT 0.100%, brokerage 0.060%, stamp duty 0.015%, GST 0.012%, exchange and SEBI 0.007% — totalling 0.394% against a dashed line at the naive 0.21% assumption.",
    imageCaption:
      "Straight from core.backtest_engine.COST_PROFILES — the same cost model the backtester charges on every trade.",
    body: [
      {
        kind: "p",
        text: "Ask a retail trader what a trade costs and you will usually hear the brokerage number. On the chart above, brokerage is the fourth-largest component and accounts for 0.060 of 0.394 percentage points. It is about a sixth of the bill.",
      },
      {
        kind: "p",
        text: "The rest is the part nobody quotes: securities transaction tax on both legs, stamp duty on the buy, exchange transaction charges, the SEBI turnover fee, GST at 18% levied on the fees, and — the largest single item — slippage, the difference between the price you saw and the price you got.",
      },
      { kind: "h", text: "The three profiles the engine ships with" },
      {
        kind: "table",
        head: ["Profile", "Round trip", "Slippage assumption"],
        rows: [
          ["India — Delivery", "0.394%", "10 bps per leg"],
          ["India — Intraday", "0.229%", "5 bps per leg"],
          ["US — Retail", "0.182%", "4 bps per leg"],
        ],
        caption: "Delivery pays full STT and stamp duty; intraday pays a reduced STT. Numbers are the engine's, not estimates.",
      },
      {
        kind: "p",
        text: "Intraday looks cheaper per trade, and it is. The catch is that people who trade intraday trade far more often, and cost scales with turnover, not with holding period.",
      },
      { kind: "h", text: "Why this decides whether a strategy is real" },
      {
        kind: "p",
        text: "Cost is not a haircut applied once. It is charged every time the position turns over. A rule that rebalances weekly puts through roughly 50 round trips a year; at 0.394% that is about 19.7% of notional annually before the strategy has predicted anything. A daily rule is far worse.",
      },
      {
        kind: "callout",
        title: "The arithmetic that kills most edges",
        text: "Annual cost drag ≈ turnover × (252 ÷ rebalance days) × round-trip cost. Halving your rebalance frequency halves the drag — and often turns a losing strategy into a marginal one without changing a single rule.",
      },
      {
        kind: "p",
        text: "This is the mechanism behind a well-documented result in the academic literature: many published anomalies look profitable gross of trading costs and stop being profitable net of them, with the highest-turnover strategies suffering most. Novy-Marx and Velikov's survey of anomaly trading costs is the standard reference, and it is the reason AlphaForge's factor lab reports a net CAGR next to the gross one rather than only the flattering figure.",
      },
      { kind: "h", text: "What to do about it" },
      {
        kind: "list",
        items: [
          "Model costs before you get attached. A backtest run at 0.21% and re-run at 0.394% can flip sign; you want to know that on day one.",
          "Treat turnover as a design parameter. If an edge only exists at daily rebalancing, it probably does not exist.",
          "Be honest about slippage. It is the biggest line item and the one most often set to zero. Size matters: your fill on a liquid large-cap is not the fill you get in a small-cap.",
          "Compare against buy-and-hold net of costs. Buy-and-hold trades roughly never, which is an advantage a strategy has to actually overcome.",
        ],
      },
      {
        kind: "quote",
        text: "A strategy that needs costs to be 0.21% to work is not a strategy. It is a rounding error with a chart.",
      },
    ],
    references: [
      { text: "Novy-Marx, R. & Velikov, M. (2016). A Taxonomy of Anomalies and Their Trading Costs. Review of Financial Studies." },
      { text: "Cost components and rates as implemented in core/backtest_engine.py — COST_PROFILES." },
    ],
    tryIt: { label: "Open the Backtester", href: "/features/backtester" },
  },

  {
    slug: "drawdowns-end-accounts-averages-dont",
    tag: "Risk",
    accent: "#a55efd",
    readMinutes: 5,
    title: "Drawdowns end accounts, averages don't",
    dek: "A loss and the gain that undoes it are not the same size. That asymmetry — not expected return — is what decides whether you are still trading in three years.",
    excerpt:
      "A strong CAGR is worthless if a 60% drawdown makes you quit first. Why position sizing, not edge, decides survival.",
    image: "/insights/drawdown.png",
    imageAlt:
      "Curve showing the gain required to recover from a drawdown: −20% needs +25%, −50% needs +100%, −70% needs +233%, with a marked ruin line at 50%.",
    imageCaption:
      "Recovery = dd ÷ (1 − dd). The 50% marker is the default ruin threshold in core.honesty.blowup_check.",
    body: [
      {
        kind: "p",
        text: "Lose 20% and you need 25% to get back. Lose 50% and you need 100%. Lose 70% and you need 233%. The curve above is not a model or an estimate — it is arithmetic, and it is the single most important shape in risk management.",
      },
      {
        kind: "p",
        text: "The consequence is that drawdown and return are not symmetric quantities that cancel out over time. A strategy averaging 15% a year that experiences a 60% drawdown has to produce years of compounding just to return to where it started, and it has to do so while you keep funding it.",
      },
      { kind: "h", text: "The part the average hides" },
      {
        kind: "p",
        text: "CAGR is a summary of the path you happened to get. It says nothing about the order of the returns, and order is what determines whether you are still in the trade. Two strategies with identical annual returns — one that grinds upward, one that halves before recovering — are not the same product. Only one of them is something a human can actually hold.",
      },
      {
        kind: "callout",
        title: "Why AlphaForge draws the line at 50%",
        text: "core.honesty.blowup_check flags any strategy whose peak-to-trough drawdown passes 50%, and the verdict cannot read PROBABLY REAL if it does — no matter how strong the Sharpe or the Deflated Sharpe. Past that point the recovery requirement exceeds 100% and, empirically, most people stop trading before they find out whether the edge was real.",
      },
      { kind: "h", text: "Sizing is the lever, not the signal" },
      {
        kind: "p",
        text: "Most effort goes into finding a better signal. Drawdown is dominated by something duller: how much you put on. Halving position size roughly halves the drawdown, and it does so with certainty, which is more than any signal offers.",
      },
      {
        kind: "list",
        items: [
          "Size to the drawdown you can actually sit through, not to the return you want. The first is a fact about you; the second is a hope about the market.",
          "Scale exposure with volatility. The same position is a different bet when realised vol doubles — the Risk module reports GARCH conditional volatility precisely because it moves before the long-run average does.",
          "Respect regime. AlphaForge's regime router cuts size in bear states and ramps it only after a bull state has persisted, because young regimes flip.",
          "Check the tail, not the average. CVaR asks what the loss looks like when the bad day happens, which is the number that ends accounts.",
        ],
      },
      {
        kind: "quote",
        text: "Survival is not a consolation prize for people without an edge. It is the precondition for an edge ever paying you.",
      },
      {
        kind: "p",
        text: "This is why every verdict in the product carries a ruin check alongside the statistics. A strategy can be genuinely predictive and still be untradeable, and a tool that only reports the Sharpe will never tell you which one you are holding.",
      },
    ],
    references: [
      { text: "Ruin threshold and drawdown logic: core/honesty.py — blowup_check, default 50%." },
      { text: "Tail measures (VaR, CVaR, GARCH conditional volatility): core/metrics.py, surfaced in the Risk module." },
    ],
    tryIt: { label: "Open Risk Analytics", href: "/features/risk" },
  },
];

export function getArticle(slug: string): Article | undefined {
  return ARTICLES.find((a) => a.slug === slug);
}
